##### ConfigMap #####
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: kong-cluster
data:
  java_options: "-Xms512m -Xmx2G -Duser.timezone=Asia/Bangkok"
  # jenkins_options: "--prefix=/jenkins --httpListenAddress=127.0.0.1 --webroot=/var/cache/jenkins/war --httpPort=$HTTP_PORT --ajp13Port=$AJP_PORT"
  jenkins_options: "--prefix=/jenkins --httpListenAddress=0.0.0.0"
  jenkins_master: "http://jenkins-master:8080"
  jenkins_name: "worker"
  jenkins_user: "jenkins"
  jenkins_retry: "10"
  jenkins_executors: "6"
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secrets
  namespace: kong-cluster
data:
  # $ echo -n "jenkins" | base64
  # amVua2lucw==
  jenkins_pass: amVua2lucw==

# ##### Google StorageClass #####
# ---
# kind: StorageClass
# apiVersion: storage.k8s.io/v1beta1
# metadata:
#   name: gcp-storage
#   namespace: kong-cluster
# provisioner: kubernetes.io/gce-pd
# parameters:
#   # type: pd-ssd
#   type: pd-standard # Default
