version: '3.2'
services:
  jenkins:
    # image: jenkins/jenkins:latest
    image: apirath/jenkins-docker:latest
    # build: ./build-jenkins
    volumes:
      - "${PWD}/jenkins_home:/var/jenkins_home"
      # - "/etc/localtime:/etc/localtime:ro"
      # - "/usr/local/bin:/user/bin"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    # privileged: true
    environment:
      JAVA_OPTS: "-Duser.timezone=ICT"
