version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.164-alpine
    volumes:
      - "${PWD}/var/jenkins_home:/var/jenkins_home"
      - "${PWD}/init.groovy:/usr/share/jenkins/ref/init.groovy.d/executors.groovy"
      # - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    environment:
      JAVA_OPTS: "-Duser.timezone=ICT"
