version: '3'
services:
  jenkins:
#    image: jenkins/jenkins:2.141
    image: apirath/jenkins-docker:v2.141-v18.06.1-ce
    volumes:
      - "${PWD}/var/jenkins_home:/var/jenkins_home"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/local/bin:/user/bin"
#      - "${PWD}/init.groovy:/usr/share/jenkins/ref/init.groovy.d/executors.groovy"
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    privileged: true
    environment:
      - JAVA_OPTS="-Duser.timezone=ICT"
