apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
spec:
  #tls:
  #- hosts:
  #  - 'jenkins.sizops.dev'
  rules:
  - host: 'jenkins.sizops.dev'
    http:
      paths:
      - backend:
          serviceName: 'jenkins'
          servicePort: 8080
